# This file was generated by GoReleaser. DO NOT EDIT.
cask "envoke" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "af409ad5bd312a1137fe41f09716c63cfeed7af3b60a33e4cdd6550168eca61d"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3319757e7e6af0abd4275d489ea17d7fb5376c1705a441c6a9d079150697ca6d"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6542e2b6e4b0293acc0993e398f6368c4873be90b3b472b13dccf766195d9b09"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59cf9e8ef2d89335c5782219fd24d0f1cf97739a9b82dc84a7ce471dc8de1e49"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envoke"
  desc "Runs shell scripts when you cd into or out of a directory"
  homepage "https://github.com/Neirda24/envoke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envoke"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envoke"]
    end
  end

  # No zap stanza required

end
