# This file was generated by GoReleaser. DO NOT EDIT.
cask "envoke" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "1035de081ec02ebe3b5219c0392d5a1d8ee37ad855ecb8826bb2119865befa08"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5208e738b882ad5278268d7cd9d4749b085da3a0b2dae5392df14ae766c46bd7"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "80dd01631fa2ef35726d14c03e21caba0d69ab8611d3fced8cea5a5b4e59df6e"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "543139326db305f17544189bb13b11f3277a235cdc8753eea1742b88ec2b1925"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envoke"
  desc "Runs shell scripts when you cd into or out of a directory"
  homepage "https://github.com/Neirda24/envoke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envoke"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envoke"]
    end
  end

  # No zap stanza required

end
