# This file was generated by GoReleaser. DO NOT EDIT.
cask "envoke" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "be19d6aa758d87c1cbadf628fc198cb8ed98924cd9e614a04fbbcc441f5466ce"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "065ce334f804dc62ac1adaa57478ce0a26bf64c7dc55cbdff9e874e4b9bd95d1"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "34dec00372bec41da1cc10ccfa238bd9551495c7b26a472261926e5897a3b9d0"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce67b2f472d66df57d02b9fbd453d23af1f1b9274a9c06e9ef9a016acd8d4075"
      url "https://github.com/Neirda24/envoke/releases/download/v#{version}/envoke_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envoke"
  desc "Runs shell scripts when you cd into or out of a directory"
  homepage "https://github.com/Neirda24/envoke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envoke"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envoke"]
    end
  end

  # No zap stanza required

end
