# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envoke < Formula
  desc "Runs shell scripts when you cd into or out of a directory"
  homepage "https://github.com/Neirda24/envoke"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Neirda24/envoke/releases/download/v0.1.0/envoke_0.1.0_darwin_amd64.tar.gz"
      sha256 "8ea3793551f7631fc728b1543d4ea38dc3a32855aa9cacc02076954fe11b4962"

      define_method(:install) do
        bin.install "envoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Neirda24/envoke/releases/download/v0.1.0/envoke_0.1.0_darwin_arm64.tar.gz"
      sha256 "07ba5bb7ded6a2ebeca17a92fb29f539db9618a85504d1c4ca28671466ea8434"

      define_method(:install) do
        bin.install "envoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Neirda24/envoke/releases/download/v0.1.0/envoke_0.1.0_linux_amd64.tar.gz"
      sha256 "808ec191ecada351a6ff2b4e2a52dbd1edebdb1422f02122779fac8d299fffda"
      define_method(:install) do
        bin.install "envoke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Neirda24/envoke/releases/download/v0.1.0/envoke_0.1.0_linux_arm64.tar.gz"
      sha256 "32275f96a17b7e1dd9b545bf4bc548d0d8670909c19ad08ef8ea973bfab7da1e"
      define_method(:install) do
        bin.install "envoke"
      end
    end
  end

  test do
    system "#{bin}/envoke", "version"
  end
end
